apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-angular
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-angular
  template:
    metadata:
      labels:
        app: frontend-angular
    spec:
      containers:
      - name: frontend-angular
        image: frontend-angular:1.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-angular
spec:
  type: NodePort
  selector:
    app: frontend-angular
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30082
